# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://dystopia2.com
title: DYS
email: dysteam@dystopia2.com
author: DYS TEAM
description: A Multiplayer Cyberpunk FPS Built on UE4
copyright: 'Copyright &copy; 2017 DYS TEAM. All Rights Reserved.'
credits: 'Credits: Development: DYS TEAM<BR/>Original Game Development : Dustin Hulm, Robert Crouch, Tim Grant'

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: discord
    url: https://discord.gg/0suJzVeTtAfItgYG
  - title: twitter
    url: https://twitter.com/DystopiaGame
  - title: patreon
    url: https://patreon.com/dysgame
